.all-contributorsrc
README.md
src/__mocks__/eslint.js
src/index.js
src/index.test.js

There was a problem with the way that eslint fix was applied which
basically resulted in test files in this project inheriting from the
`eslintConfig` from _this project_ (`prettier-eslint`). So I added
`useEslintrc: false` to the config which I believe will fix the issue
(can be overridden)
Also added a test for the README example so this doesn't happen again!
Could I get a review from @exdeniz and @demoneaux (and anyone else interested? ping @gyandeeps?)
Closes #2

fix(eslint): config will not use eslintrc from this project

---

README.md
src/index.js
src/index.test.js

So you can specify whether to use your project's version of `eslint` or
`prettier` (if they don't match up for some reason). Or even :shudder:
use a global version :shudder:.
This will be especially useful for the CLI and the atom plugin I think.
Closes #3
Could I get at least one review on this from anyone? :)

feat(path): add `eslintPath` and `prettierPath` options

---

README.md
src/index.js
src/index.test.js

Provides for configuration of whether to dump the `eslintConfig` and `prettierOptions` to the console, defaults to false.

WIP: add `sillyLogs` option

---

.all-contributorsrc
README.md
package.json
src/utils.js
src/utils.test.js
yarn.lock

Currently, if you try to specify `max-len` using the `options`-object rather than a number, `prettier` is called with `printWidth: 80`.
```
"rules": {
"max-len": ["error", { 
"code": 120,
...
}],
...
},
```
With this PR, we handle this case by looking at the `code`-property and use that as the option to `prettier`

fix(prettierOptions): Handle max-len with object configuration

---

README.md
package.json
src/__mocks__/fs.js
src/__mocks__/loglevel.js
src/index.js
src/index.test.js
src/log.js
src/log.test.js
src/utils.js
src/utils.test.js
yarn.lock

BREAKING CHANGE: `disableLog` and `sillyLogs` no longer available. You should use `logLevel` instead
**before**:
```javascript
format({disableLog: true})
```
**after**:
```javascript
format({logLevel: 'silent'})
```
**before**:
```javascript
format({sillyLogs: true})
```
**after**:
```javascript
format({logLevel: 'trace'})
```

feat(logging): add really nice logging capabilities

---

.all-contributorsrc
README.md
src/index.test.js
src/utils.js
src/utils.test.js

The `bracketSpacing` option for prettier can be inferred from the eslint [`object-curly-braces`][curly] config. Correct me if I am wrong on the assumption 😉.
The [options][curly-options] for the `object-curly-spacing` will work without any extra configuration. Tests have been added to confirm/track this assertion.
P.S. Stumbled onto fixing this by reading kentcdodds/prettier-eslint-cli#26! It doesn't resolve the issue, but it should help it along I suppose.
[curly]: http://eslint.org/docs/rules/object-curly-spacing
[curly-options]: http://eslint.org/docs/rules/object-curly-spacing#options

fix(prettierOptions): add eslint config inference for 'bracketSpacing'

---

src/index.js
src/index.test.js
src/utils.test.js

This fixes #51 because after it we try to read eslint config even if eslintConfig is provided.
Unfortunately it also means eslint will crash if .eslintrc is not present. This change makes
.eslintrc presence optional.

fix: Allow for no presence of .eslintrc

---

src/index.js

This prevents yet another artifact introduced by my previous PR. Specifically the output of prettier-eslint looks like following when no .eslintrc is present:
```
prettier-eslint [WARN]: Unable to find config
prettier-eslint [WARN]: Unable to find config
prettier-eslint [WARN]: Unable to find config
prettier-eslint [WARN]: Unable to find config
prettier-eslint [WARN]: Unable to find config
prettier-eslint [WARN]: Unable to find config
prettier-eslint [WARN]: Unable to find config
success formatting 2 files with prettier-eslint
5 files were unchanged
```
This fixes it by changing log level to debug

fix: Make prettier-eslint less verbose when no .eslintrc

---

src/utils.js
src/utils.test.js

This is in line with eslint's defaults for string values: http://eslint.org/docs/rules/comma-dangle.
Fixes https://github.com/prettier/prettier-eslint/issues/69.

fix: trailingComma all only if functions enabled

---

package.json
src/utils.test.js
yarn.lock

Hello !
As there have been some minor changes in prettier, this PR upgrades **prettier** to **1.3.0** ! Also ran fix which only generated change in : `src/utils.test.js`
If I can improve this PR, I'll be glad to do so 😄 !

feat: upgrade prettier to 1.3.0

---

src/index.test.js
src/utils.js
src/utils.test.js

The defaultValue param's are not matching Prettier's defaults in these lines:
- https://github.com/prettier/prettier-eslint/blob/master/src/utils.js#L198 (should be `false`)
- https://github.com/prettier/prettier-eslint/blob/master/src/utils.js#L215 (should be 'none') 
- https://github.com/prettier/prettier-eslint/blob/master/src/utils.js#L243 (should be `true`)
This PR fixes this.

Correct Prettier defaults

---

README.md
src/index.js
src/index.test.js

Prettier supports the `parser` option to indicate the parser to be used when parsing text rather than a file.
This is necessary because it's difficult to detect the source file type without a file extension.
This fix uses the same logic Prettier does to determine if the parser should be `postcss`.
It also avoids running ESLint on .css, .less, and .scss files.

setting prettier parser option for CSS files

---

src/index.js

According to https://github.com/prettier/prettier-eslint/blob/bee9283f005fda2b08d1940f4455169333effa07/src/utils.js#L47

options.eslintConfig is an object, not a string

---

README.md

`prettierLast` was misspelled as `pretterLast`

docs(readme): Fix typo of prettierLast option

---

.babelrc
.eslintrc
package.json
src/__mocks__/eslint.js
src/__mocks__/prettier.js
src/__tests__/index.js
src/__tests__/utils.js
src/index.js
src/utils.js
tests/fixtures/paths/node_modules/prettier/index.js
tests/fixtures/paths/package.json

This actually is a partial solution to #118.
BREAKING CHANGE: the API is now async 100% of the time. It's a shame, but we have to do that due to the async nature of resolving the prettier config.
I'd really appreciate a review on this. I'm going to publish a `beta` which you can install with `prettier-eslint@beta`. I'll also publish a beta of `prettier-eslint-cli` soon. Please give it a go!

feat: support prettier configuration

---

src/index.js

Prettier options provided to the format function should override
prettier options found in config file.

Change prettier config precedence

---

package.json
src/__tests__/index.js
src/index.js

This should allow `.ts`/`.tsx` files to be run through `prettier` and `eslint` with proper parser settings.

Add basic support for typescript files

---

.babelrc
src/__mocks__/prettier.js
src/__tests__/index.js
src/index.js

Prettier's resolveConfig function has a .sync function that doesn't require async handling:
https://github.com/prettier/prettier#prettierresolveconfigfilepath--options

feat(format): make format synchronous

---

package.json
src/__mocks__/fs.js

Upgrade prettier to [1.7.0](https://github.com/prettier/prettier/issues/2804) to help fix https://github.com/prettier/prettier-eslint-cli/issues/105.
Some tests were (already) failing with:
```
JSONError: JSON Error in /Users/ppvg/github/prettier-eslint/mock/package.json:
Unexpected token 'v' at 1:1
var fake = true
^
```
So the `fs` mock now matches on filename and returns either the original fake or a fake `package.json`. I'm not sure whether that's considered too ugly of a hack.

Upgrade prettier to 1.7.0

---

CHANGELOG.md

Hi,
current link leads to a 404 while on master.
Those relative links seems pretty fragile actually.

Fix releases path in changelog link

---

src/__tests__/index.js
src/index.js

Some people still want to use older versions of prettier which does not have the
`resolveConfig.sync` method defined. In this case we will now just pretend like there was a prettier
config but that it was empty.

fix(backward-compatibility): don't throw if resolveConfig.sync is undefined

---

package.json
src/index.js

This will remove warning about not using postcss any longer. This will use the language specific parser options for prettier.

Don't use postcss parser

---

src/__tests__/index.js
src/index.js

If we forward all text with it's filepath, if there is one, prettier will figure out which parser it should use. This will make this package support all future parsers prettier will add, by default.
We only have to check which files to forward to eslint which is something that changes less frequently. For now we forward files with extension defined in eslint config or default to .js/.jsx/.ts/.tsx files.
Let's compare this approach with #144 and see which we should use.

feat(prettier): Forward all text to prettier

---

src/__mocks__/eslint.js
src/__tests__/index.js
src/index.js
src/utils.js

ESLint always lint with all rules you provide, even if you call it with the fix command.
It does this to be able to show you information about the rules it could not fix.
We don't display those messages, so we can remove all unfixable rules and allow ESLint to do less work and in turn run faster.

feat(perf): Remove unfixable rules

---

src/__mocks__/fs.js
src/__tests__/index.js

Closed #202.
Changes,
- The key one is adding `prettier` field in the mocked `package.json`, which prevents `cosmiconfig`, a hidden dependency of `prettier`, from searching other candidate files. Because [cosmiconfig@5](https://github.com/davidtheclark/cosmiconfig/blob/master/CHANGELOG.md#501) switched from `require-from-string` to `require`. If trying to require a nonexistent file, it will throw an error like `Cannot find module .prettierrc.js`.
- I also updated the Vue example input&output, because `prettier` has changed its behaviour since our last successful build (prettier@1.13.5 and now is 1.18.2). Empty template tag is easy to trigger edge cases and not very common, so a div was added.
Some concerns during fixing (if needed I can open an issue),
- "resolves to the local eslint …

fix: failed CI due to prettier upgrade

---

package.json
src/__tests__/index.js
src/utils.js

Update to Eslint 6
Apparently any call to CLIEngine(eslintOptions) where eslintOptions doesn't contain a cwd nor a ignore set to false, will lead to reading the eslintignore twice now.
You can try the branch with: 
``` $ yarn add prettier-eslint@hamzahamidi/prettier-eslint#bundles ```
Or 
``` $ npm install --save prettier-eslint@hamzahamidi/prettier-eslint#bundles ```

feat(Eslint): Update to Eslint 6

---

package.json
src/__tests__/index.js
src/utils.js

This reverts commit 47acf7c6f88690ecb8a417404fb66bd74b1e0509.
The pr for Upgrading to eslint 6 no longer pass https://travis-ci.org/github/prettier/prettier-eslint/builds/689775135

Revert "Feat(Eslint): Upgrade to Eslint 6 (#254)"

---

package.json
src/index.js

build: upgrade to prettier v2

---

.all-contributorsrc
.travis.yml
README.md
package.json

- upgrades eslint to the latest version as suggested in #401 
- updates contributors list as described in the [contributing guidelines](https://github.com/prettier/prettier-eslint/blob/master/CONTRIBUTING.md)

Support ESLint 7 (fixes #401)

---

babel.config.js
src/index.js

As the `package.json` already specifies node runtime to be >= 10.x, `core-js` fallback is not necessary. Additionally, it is causing execution error when core-js (at any version!) is not already installed. Replaces also PR #359.

remove extraneous core-js imports

---

.all-contributorsrc
.eslintrc.js
.github/workflows/ci.yml
.prettierrc.js
README.md
package.json
src/__mocks__/eslint.js
src/__tests__/index.js
src/__tests__/utils.js
src/index.js
src/utils.js
tests/fixtures/paths/node_modules/eslint/index.js

Closes #656
These are breaking changes as the ESLint API has changed with version 8.
Major change is that `format` is now asynchronous. This is because the `executeOnText` function (now `lintText`) https://github.com/eslint/eslint/blob/851f1f18bd1a5da32c1b645bfcb28fadc627ad9e/lib/eslint/eslint.js#L572 is asynchronous. I would have made my changes backward compatible, but there is no backward compatible method for the asynchronous change.

feat: :sparkles: Support ESLint 8

---

.npmrc

BREAKING CHANGE: Only works with ESLint 8. ESLint 8 API changes caused the `format` function to now be asynchronous.

ci(GitHub): :green_heart: Use HTTPs for npm publish

---

jest.config.js
src/index.js

I missed one `await` call that is causing a bug. Unfortunately, the moment I added the `await` the test coverage dropped. The reason being is that setting `sync` in this test to `undefined` isn't working.
https://github.com/prettier/prettier-eslint/blob/e09c913763967782f8d5df7dfc31ee1124cf512d/src/__tests__/index.js#L390-L401
I've tried several things and cannot get mock function to be set to `undefined`. I think putting out the hotfix is more important than getting coverage to work.

fix: :ambulance: Fix missing `await`

---

src/index.js

While working on `prettier-eslint-cli`, the CLI tests were failing because of an error about invalid ESLint configuration. Come to find out more ESLint configurations exist, namely:
* ignorePatterns
* plugins
* env
* settings
* noInlineConfig

fix: :ambulance: Fix invalid ESLint configuration error

---

package.json
tsconfig.json
types/index.d.ts

Moved here from DefinitelyTyped/DefinitelyTyped#54526 - see context in #575.
@kylemh

feat: ✨ Add TypeScript definitions

---

.all-contributorsrc
README.md
src/__tests__/utils.js
src/utils.js

prettier/prettier@4992d9720, released in 2.4.0, deprecated the
`jsxBracketSameLine` option in favor of a new, more generic option,
`bracketSameLine`. See docs:
https://prettier.io/docs/en/options.html#bracket-line
This has caused a warning
>  jsxBracketSameLine is deprecated.
for people using Prettier 2.4.0+, if their ESLint config leads us to
infer and use a value for jsxBracketSameLine.
So, instead of inferring and using a value for jsxBracketSameLine,
do so for the new bracketSameLine.
In d8bf1e3dc, which we released in 14.0.0, we stopped supporting
Prettier versions older than 2.5.1. That means we don't need to
maintain backward-compatible code for users with Prettier <2.4.0,
which doesn't have bracketSameLine.
See discussion: …

chore(prettier): Take Prettier 2.4.0's jsxBracketSameLine → bracketSameLine

---

src/index.js
types/index.d.ts

The function declaration was changed in #696 from `function format(options)` to `async function(options)`, the example section in README.md is changed as well, but the doc as well as the later added `types/index.d.ts` from #739 was not updated.

Fix the return type of format: string -> Promise<string>

---

.husky/pre-commit
package.json

fixes #746
Getting rid old really old transitive husky@2 dependencies.
Husky v8:
- Zero dependencies and lightweight (6 kB)
- Powered by modern new Git feature (core.hooksPath)
- Follows npm and Yarn best practices regarding autoinstall
`opt-cli` seems to be abandoned (last update 5 years ago).
Looks like this dependency is not needed anymore with the new Husky. (couldn't find other references/usage in the project)

chore: upgrade husky to v8

---

types/index.d.ts

It looks like `logLevel` in README has the value 'silent' and 'slient' does work.

Completing the missing LogLevel values 'silent'

---

README.md

for now prettier-vscode removed support of  prettier-eslint
https://github.com/prettier/prettier-vscode/commit/f6ae3f6268b4a711e425b4caddcf99b435899b15
https://github.com/prettier/prettier-vscode/issues/958

update vs-code plugin

---

.changeset/fair-foxes-brake.md
package.json
src/__tests__/index.js
src/index.js

Without this addition, prettier-eslint will only run the Prettier step for .svelte files, but NOT the Eslint step!
close #525

feat: support handling `.svelte` files
